require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'

  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.0

#################### Bundler ###########################

Bundler/OrderedGems:
  Enabled: true
  ConsiderPunctuation: true

#################### Layout ###########################
Layout/EmptyLinesAroundAttributeAccessor:
  StyleGuide: '#empty-lines-around-attribute-accessor'
  Enabled: true

Layout/LineLength:
  Exclude:
    - 'test/**/*'

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

#################### Lint ##################################

Lint/AmbiguousBlockAssociation:
  StyleGuide: '#syntax'
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/FloatComparison:
  StyleGuide: '#float-comparison'
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: true

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'db/seeds.rb'
    - 'config/routes.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  StyleGuide: '#short-methods'
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  StyleGuide: '#too-many-params'
  Enabled: false

#################### Naming ##############################
Naming/PredicateName:
  StyleGuide: '#bool-methods-qmark'
  Enabled: true
  ForbiddenPrefixes:
    - is_

#################### Style ###############################
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  StyleGuide: '#hash-literal-as-last-array-item'
  Enabled: true
  EnforcedStyle: no_braces

Style/HashSyntax:
  StyleGuide: '#hash-literals'
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/RedundantFetchBlock:
  Reference: 'https://github.com/JuanitoFatas/fast-ruby#hashfetch-with-argument-vs-hashfetch--block-code'
  Enabled: true

Style/RedundantFileExtensionInRequire:
  StyleGuide: '#no-explicit-rb-to-require'
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/StringLiterals:
  StyleGuide: '#consistent-string-literals'
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInArguments:
  StyleGuide: '#no-trailing-params-comma'
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  StyleGuide: '#no-trailing-array-commas'
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInBlockArgs:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

# Rails cops from rubocop-rails
# https://github.com/rubocop-hq/rubocop-rails/blob/master/config/default.yml
Rails/ActiveRecordCallbacksOrder:
  StyleGuide: 'https://rails.rubystyle.guide/#callbacks-order'
  Enabled: true

Rails/DefaultScope:
  StyleGuide: 'https://rails.rubystyle.guide#avoid-default-scope'
  Enabled: true

Rails/FilePath:
  EnforcedStyle: slashes

Rails/FindById:
  StyleGuide: 'https://rails.rubystyle.guide/#find'
  Enabled: true

Rails/Inquiry:
  StyleGuide: 'https://rails.rubystyle.guide/#inquiry'
  Enabled: true

Rails/MailerName:
  StyleGuide: 'https://rails.rubystyle.guide/#mailer-name'
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  StyleGuide: 'https://rails.rubystyle.guide/#ids'
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  StyleGuide: 'https://rails.rubystyle.guide/#inline-rendering'
  Enabled: true

Rails/RenderPlainText:
  StyleGuide: 'https://rails.rubystyle.guide/#plain-text-rendering'
  Enabled: true

Rails/ShortI18n:
  StyleGuide: 'https://rails.rubystyle.guide/#short-i18n'
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/WhereExists:
  Enabled: true

Rails/ContentTag:
  Enabled: false
